# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-11-24 09:30+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=CHARSET\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../gecosws_config_assistant/view/LogTerminalDialog.py:135
msgid "Log terminal"
msgstr ""

#. Error adding GEMs repository
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:121
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:128
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:135
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:148
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:161
#: ../gecosws_config_assistant/view/GecosCCSetupProgressView.py:168
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:412
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:418
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:425
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:437
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:474
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:487
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:612
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:630
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:644
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:665
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:756
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:772
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:802
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:826
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:850
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:871
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:891
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:944
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:957
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:984
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:995
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1003
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1012
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1024
msgid "ERROR"
msgstr ""

#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:175
msgid "Disconnect from CC GECOS"
msgstr ""

#: ../gecosws_config_assistant/view/ConnectWithGecosCCDialog.py:177
msgid "Connect to CC GECOS"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:100
msgid "System status"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:105
#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:108
msgid "Assistant version: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:109
msgid "UNKNOWN VERSION"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:114
msgid "Workstation name: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:120
msgid "Time server: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:123
msgid "Network interfaces: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:131
msgid "GECOS Control Center connection data: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:135
msgid "Server URL:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:136
msgid "Login:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:139
msgid "Local users: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:146
msgid "User authentication method: "
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:149
msgid "Method:"
msgstr ""

#. text
#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:152
#: ../gecosws_config_assistant/view/UserAuthDialog.py:290
#: ../gecosws_config_assistant/view/UserAuthDialog.py:331
msgid "Domain:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:154
#: ../gecosws_config_assistant/view/UserAuthDialog.py:291
#: ../gecosws_config_assistant/view/UserAuthDialog.py:332
msgid "Workgroup:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:158
msgid "Server URI:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:160
#: ../gecosws_config_assistant/view/UserAuthDialog.py:248
msgid "Users base DN:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:162
msgid "Groups base DN:"
msgstr ""

#: ../gecosws_config_assistant/view/SystemStatusElemDialog.py:167
msgid "No status data!"
msgstr ""

#: ../gecosws_config_assistant/view/ADSetupDataElemView.py:125
msgid ""
"Can't connect to Active Directory.\n"
"Please double-check all the fields"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:69
#: ../gecosws_config_assistant/view/UserAuthDialog.py:165
#: ../gecosws_config_assistant/view/UserAuthDialog.py:212
#: ../gecosws_config_assistant/controller/MainMenuController.py:235
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:248
#: ../gecosws_config_assistant/dto/LocalUsersAuthMethod.py:47
#: ../gecosws_config_assistant/tests/dto/LocalUsersAuthMethodTest.py:39
msgid "Internal"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:69
#: ../gecosws_config_assistant/view/UserAuthDialog.py:167
#: ../gecosws_config_assistant/view/UserAuthDialog.py:214
#: ../gecosws_config_assistant/controller/MainMenuController.py:231
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:250
#: ../gecosws_config_assistant/dto/LDAPAuthMethod.py:48
#: ../gecosws_config_assistant/tests/dto/LDAPAuthMethodTest.py:40
msgid "LDAP"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:69
#: ../gecosws_config_assistant/view/UserAuthDialog.py:169
#: ../gecosws_config_assistant/view/UserAuthDialog.py:216
#: ../gecosws_config_assistant/controller/MainMenuController.py:233
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:252
#: ../gecosws_config_assistant/dto/ADAuthMethod.py:45
#: ../gecosws_config_assistant/tests/dto/ADAuthMethodTest.py:40
msgid "Active Directory"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:244
msgid "Please fill the data to setup the LDAP authentication method."
msgstr ""

#. text
#: ../gecosws_config_assistant/view/UserAuthDialog.py:247
msgid "LDAP server URI:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:249
msgid "Groups base DN (optional):"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:250
msgid "Bind user DN (optional):"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:251
msgid "Bind user password (optional):"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:286
msgid ""
"Please fill the data to setup the Active Directory authentication method."
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:292
msgid "(Active Directory) User:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:293
msgid "(Active Directory) Password:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:327
msgid ""
"Specific configuration data was loaded from GECOS server\n"
"(sssd.conf, krb5.conf, smb.conf and pam.conf)"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:333
msgid "User:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:334
msgid "Password:"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:362
msgid ""
"There is no necessary data to setup the local users authentication method."
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:513
msgid "An error happened while saving the users authentication method!"
msgstr ""

#: ../gecosws_config_assistant/view/UserAuthDialog.py:515
#: ../gecosws_config_assistant/controller/NTPServerController.py:96
#: ../gecosws_config_assistant/controller/NTPServerController.py:102
msgid "See log for more details."
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:95
msgid "Modifiy local user"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:101
msgid "Add local user"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:137
msgid "The password confirmation field is empty!"
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:138
#: ../gecosws_config_assistant/controller/AutoSetupController.py:115
#: ../gecosws_config_assistant/controller/AutoSetupController.py:206
#: ../gecosws_config_assistant/controller/AutoSetupController.py:218
#: ../gecosws_config_assistant/controller/LocalUserController.py:85
#: ../gecosws_config_assistant/controller/LocalUserController.py:102
#: ../gecosws_config_assistant/controller/LocalUserController.py:111
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:419
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:438
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:474
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:507
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:517
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:527
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:128
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:149
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:160
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:258
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:276
msgid "Please fill all the mandatory fields."
msgstr ""

#: ../gecosws_config_assistant/view/LocalUserElemDialog.py:147
msgid "The password confirmation is different from password"
msgstr ""

#: ../gecosws_config_assistant/view/NTPServerElemView.py:129
msgid ""
"Can't connect with NTP server.\n"
"Please double-check the NTP server address"
msgstr ""

#: ../gecosws_config_assistant/view/NTPServerElemView.py:133
msgid "NTP server connection successful"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:84
msgid "GECOS Config Assistant"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:209
msgid "Link with GECOS server"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:211
msgid ""
"You must link your workstation with a GECOS server to be \n"
"able to manage this workstation in a centralized way"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:222
msgid "Setup user authentication method"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:224
msgid ""
"You must setup the user authentication method to either: internal users, "
"LDAP or Active Directory"
msgstr ""

#: ../gecosws_config_assistant/view/MainWindow.py:410
msgid "Unlink"
msgstr ""

#: ../gecosws_config_assistant/view/SplashScreen.py:55
msgid "Loading ..."
msgstr ""

#: ../gecosws_config_assistant/util/GtkAptProgress.py:251
#, python-format
msgid "Downloading file %(current)li of %(total)li with %(speed)s/s"
msgstr ""

#: ../gecosws_config_assistant/util/GtkAptProgress.py:257
#, python-format
msgid "Downloading file %(current)li of %(total)li"
msgstr ""

#. Setup some child widgets
#: ../gecosws_config_assistant/util/GtkAptProgress.py:280
msgid "Details"
msgstr ""

#: ../gecosws_config_assistant/util/GtkAptProgress.py:354
msgid "Starting..."
msgstr ""

#: ../gecosws_config_assistant/util/GtkAptProgress.py:360
msgid "Complete"
msgstr ""

#: ../gecosws_config_assistant/controller/NTPServerController.py:95
#: ../gecosws_config_assistant/controller/NTPServerController.py:101
msgid "Error saving NTP server data."
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:200
msgid "This workstation has got a network connection configured"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:203
msgid "This workstation has NO network connection"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:207
msgid "This worstation has loaded setup data values from Control Center"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:210
msgid "This workstation can load setup data values from Control Center"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:214
msgid "This workstation is synchronized with a time server (NTP)"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:217
msgid "This workstation is NOT synchronized with a time server (NTP)"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:221
msgid "This workstation is linked to a Control Center"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:224
msgid "This workstation is NOT linked to a Control Center"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:226
#, python-format
msgid "Users authenticate themselves with %s"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:318
#: ../gecosws_config_assistant/controller/MainMenuController.py:356
msgid "Upgrading ..."
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:368
msgid "Unable to connect to software repository"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:374
msgid "An error occurred during the upgrade"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:384
msgid "Installing gems ..."
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:395
msgid "An error ocurred while installing gems"
msgstr ""

#: ../gecosws_config_assistant/controller/MainMenuController.py:405
msgid "GECOS Config Assistant has been udpated. Restarting ..."
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:113
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:126
msgid "The URL field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:123
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:136
msgid "Malformed URL in URL field!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:124
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:138
msgid "Please double-check it."
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:152
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:188
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:576
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:726
msgid "The certificate of this server is expired!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:156
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:191
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:580
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:730
msgid "The certificate of this server is not trusted!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:161
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:196
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:585
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:735
msgid "Do you want to disable the SSL certificate verification?"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:164
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:199
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:588
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:738
msgid "Subject:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:167
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:201
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:591
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:740
msgid "Issuer:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:170
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:204
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:595
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:743
msgid "Serial Number:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:172
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:206
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:597
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:745
msgid "Not before:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:174
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:208
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:599
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:747
msgid "Not after:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:195
#: ../gecosws_config_assistant/controller/AutoSetupController.py:227
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:230
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:240
msgid "Can't connect to GECOS CC!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:196
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:231
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:634
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:776
msgid "SSL ERROR:"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:205
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:147
msgid "The Username field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:217
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:158
msgid "The Password field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:228
msgid "Please double-check all the data and your network setup."
msgstr ""

#. Show process view
#. Get auto setup JSON
#: ../gecosws_config_assistant/controller/AutoSetupController.py:249
msgid "Please wait"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:259
msgid "Error getting data"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:261
msgid "Can't read auto setup configuration data from GECOS Control Center!"
msgstr ""

#: ../gecosws_config_assistant/controller/AutoSetupController.py:267
msgid "Success getting data from GECOS server"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:84
msgid "The login field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:93
msgid "The login field contains not allowed characters!"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:101
msgid "The name field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:111
msgid "The password field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:119
msgid "The password field contains not allowed characters."
msgstr ""

#: ../gecosws_config_assistant/controller/LocalUserController.py:168
msgid "Do you really want to delete this user? "
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:339
msgid ""
"The user authentication data has changed.\n"
"Do you want to setup the user authentication method using this new data?"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:387
msgid "Authentication method saved!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:391
msgid "Authentication method failed!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:418
msgid "The URI field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:427
msgid "Malformed LDAP URI!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:428
msgid "Please check that the URI starts with 'ldap(s)://'."
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:437
msgid "The users base DN field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:445
msgid "Can't connect to LDAP server!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:446
#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:536
msgid "Please check all the fields and your network connection."
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:463
msgid "Bad netbios hostname!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:464
msgid "Please change the hostname of this computer."
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:473
msgid "The Domain field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:494
msgid "Can't resolv the Active Directory Domain name!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:496
msgid "Please check the Domain field and your DNS configuration."
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:506
msgid "The Workgroup field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:516
msgid "The AD administrator user field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:526
msgid "The AD administrator password field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/UserAuthenticationMethodController.py:535
msgid "Can't connect to Active Directory server!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:241
msgid "Please double-check all the data and yournetwork setup."
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:256
msgid "The GECOS workstation name field is empty!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:274
msgid "You must select an OU!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:290
msgid "Can't obtain data from OU!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:292
msgid "Please double check the selected OU."
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:306
msgid "The GECOS workstation name already exist!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:308
msgid "Please choose a different name."
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:402
msgid "Link to Chef"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:403
msgid "Register in GECOS CC"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:408
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:432
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:444
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:679
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:863
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:904
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:939
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:951
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:964
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:974
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1021
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1033
msgid "IN PROCESS"
msgstr ""

#. We don't need any certificate to unlink from Chef or GECOS CC
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:429
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:441
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:676
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:860
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:901
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:906
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:948
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:961
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:971
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1018
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1030
#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1035
msgid "DONE"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:477
msgid "There was an error while getting the client certificate"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:490
msgid "There was an error while saving the client certificate"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:633
msgid "Can't connect to GEMs repository!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:647
msgid "There was an error while adding the GEMs repository:\n"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:668
msgid "There was an error while installing a required GEM: "
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:775
msgid "Can't connect to Chef Server!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:805
msgid "Can't create/modify /etc/chef/client.rb file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:828
msgid "Can't link to chef server!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:852
msgid "Can't create/modify /etc/chef.control file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:873
msgid "Can't register the computer in GECOS CC"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:893
msgid "Can't save /etc/gcc.control file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:928
msgid "Local disconnection done!"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:933
msgid "Unlink from Chef"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:934
msgid "Unregister from GECOS CC"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:986
msgid "Can't unregister the computer from GECOS CC"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:997
msgid "Can't remove /etc/chef.control file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1005
msgid "Can't remove /etc/chef/client.pem file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1014
msgid "Can't delete Chef node"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1026
msgid "Can't remove /etc/gcc.control file"
msgstr ""

#: ../gecosws_config_assistant/controller/ConnectWithGecosCCController.py:1059
msgid "Can't get OUs from GECOS Control Center"
msgstr ""
